### ISSUE TITLE
mdac_typ.exe fails to install

### ISSUE THREAD

**Issue by svmnotn** [Nicals/aurora_linux#8]
`Note: command wine mdac_typ.exe returned status 5. Aborting.`
The window just said, something went wrong during the installation.

**Comment by svmnotn** [comment]
```
Using winetricks 20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615 with wine-3.11 (Staging) and WINEARCH=win32
Executing w_do_call mdac28
Executing load_mdac28 
Using native,builtin override for following DLLs: mtxdm odbc32 odbccp32 oledb32
Executing wine regedit C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing wine regedit C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/svmnotn/.cache/winetricks/mdac28
Executing wine mdac_typ.exe
0070:err:richedit:ReadStyleSheet skipping optional destination
0070:err:richedit:ReadStyleSheet skipping optional destination
0070:err:richedit:ReadStyleSheet skipping optional destination
0070:err:richedit:ReadStyleSheet skipping optional destination
0070:err:richedit:ReadStyleSheet skipping optional destination
0074:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\svmnotn\\Temp\\IXP000.TMP\\msvcrt.CAB"
0074:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\svmnotn\\Temp\\IXP000.TMP\\mtxfiles.CAB"
0074:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\svmnotn\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0074:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\svmnotn\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0074:err:setupapi:SetupDefaultQueueCallbackW copy error 32 L"C:\\users\\svmnotn\\Temp\\IXP000.TMP\\msdaorar.dll" -> L"C:\\Program Files\\Common Files\\System\\OLE DB\\msdaorar.dll"
------------------------------------------------------
Note: command wine mdac_typ.exe returned status 5. Aborting.
------------------------------------------------------
Something went wrong. Aurora is not installed.
```
Is what I get when trying to install

**Comment by AlfredDobradi** [comment]
I just commented that line out, mdac27 is installed earlier anyway and 2.8 is not a hard requirement, everything seems to be working. Couldn't find anything useful about it even though there were reports of the same issue scattered.

```
  regsvr32 msjet40.dll
  #$winetricks mdac28
```

**Comment by Nicals** [comment]
I don't remember why mdac28 was set as a dependency.
I know I found a lot of different method to make Aurora running under Wine, and mdac28 was said to be needed.

I think I tried to check every dependencies to make sure they were indeed necessary to run the game.
Some of them didn't prevent the game from running if not installed, but some VB error message popped-up from time to time without them.
Unfortunaly, I did not document this process, so I really can't tell which one seemed really required for Aurora, and which one was just installed because of something I read on Aurora subreddit or official forum.

Can you confirm that Aurora runs smoothly with mdac27 and you don't have any VB error message ?
If so, I will remove the mdac28 dependency and hope all goes well.

I also would like to know what causes the original issue, but couldn't reproduce it on my local machine, nor could I found anything satisfying on the internet.

**Comment by AlfredDobradi** [comment]
I didn't have any errors - played for an hour or so - although my galaxy screen is just blue without any markers (not sure if it's related to the absence of 2.8)

**Comment by AlfredDobradi** [comment]
I did a fresh install recently and everything went perfectly, no issues with mdac28.

**Comment by Nicals** [comment]
I found some info on this bug: https://bugs.winehq.org/show_bug.cgi?id=45627

Wine version should be > 3.21 in order to install mdac28
